---
name: DNSControl Action
description: Deploy your DNS configuration to multiple providers
author: Koen Rouwhorst <info@koenrouwhorst.nl>
branding:
  icon: cloud
  color: yellow
inputs:
  args:
    description: DNSControl command
    required: true
runs:
  using: docker
  image: 'Dockerfile'
