---
on: push
name: build
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Dockerfilelint
        uses: docker://replicated/dockerfilelint
        with:
          args: Dockerfile

      - name: Bats
        uses: koenrh/actions/bats@master
        with:
          args: test/*.bats

      - name: ShellCheck
        run: shellcheck entrypoint.sh
